"""time

Revision ID: 034024cba87c
Revises: 25da2beab40d
Create Date: 2021-08-19 00:36:40.874713

"""

# revision identifiers, used by Alembic.
revision = '034024cba87c'
down_revision = '25da2beab40d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
