"""chat_id

Revision ID: 3ba7a159a958
Revises: 92d347548056
Create Date: 2021-08-28 22:18:48.807551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3ba7a159a958"
down_revision = "92d347548056"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("chat_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "chat_id")
    # ### end Alembic commands ###
