"""time

Revision ID: 92d347548056
Revises: 66de04a29b40
Create Date: 2021-08-28 22:14:42.876722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "92d347548056"
down_revision = "66de04a29b40"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
