"""subs_update

Revision ID: d8c2036ee771
Revises: 034024cba87c
Create Date: 2021-08-19 01:28:37.946852

"""

# revision identifiers, used by Alembic.
revision = 'd8c2036ee771'
down_revision = '034024cba87c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
