version: "2.4"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSGRES_DB: habr_db
    healthcheck:
      test: POSTGRES_PASSWORD=pass pg_isready -q -U user -d habr_db
  api:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - postgres