"""time in subs

Revision ID: 25da2beab40d
Revises: d110b20d4945
Create Date: 2021-08-19 00:25:29.467109

"""

# revision identifiers, used by Alembic.
revision = "25da2beab40d"
down_revision = "d110b20d4945"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
