"""time

Revision ID: 66de04a29b40
Revises: 2cb9c7521abc
Create Date: 2021-08-28 22:05:01.702080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "66de04a29b40"
down_revision = "2cb9c7521abc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions", sa.Column("last_update", sa.DateTime(), nullable=True)
    )
    op.add_column("users", sa.Column("chat_id", sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "chat_id")
    op.drop_column("subscriptions", "last_update")
    # ### end Alembic commands ###
