"""time

Revision ID: 675fa7098085
Revises: 3ba7a159a958
Create Date: 2021-09-02 14:36:34.230590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675fa7098085'
down_revision = '3ba7a159a958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('tag', sa.ARRAY(sa.String(length=64)), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
