"""subs

Revision ID: d110b20d4945
Revises: 432792f39072
Create Date: 2021-08-19 00:21:19.797030

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d110b20d4945"
down_revision = "432792f39072"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subscriptions", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "subscriptions", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subscriptions", type_="foreignkey")
    op.drop_column("subscriptions", "user_id")
    # ### end Alembic commands ###
